workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "net.coventry.sleepless"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - production
      ios_signing:
        distribution_type: app_store
        bundle_identifier: net.coventry.sleepless
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Upload debug symbols to Firebase Crashlytics
        script: |
          if [ "$FCI_BUILD_TYPE" == "release" ]; then
            echo "Uploading debug symbols to Firebase Crashlytics"
            find "$FCI_BUILD_DIR/build/ios/archive/Runner.xcarchive/dSYMs" \
              -name "*.dSYM" \
              -exec "$FCI_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols" \
              -gsp "$FCI_BUILD_DIR/ios/Runner/GoogleService-Info.plist" \
              -p ios {} +
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false