workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - production
      vars:
        PACKAGE_NAME: "net.coventry.sleepless"
      flutter: stable
    scripts:
      - name: Run unit tests
        script: |
          flutter test --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Build Android
        script: |
          flutter build appbundle --release \
            --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
          flutter build apk --release \
            --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Upload Android debug symbols
        script: |
          cd android && ./gradlew crashlyticsUploadSymbolsRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - production
      ios_signing:
        distribution_type: app_store
        bundle_identifier: net.coventry.sleepless
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Increment build number
        script: |
          #!/bin/sh
          cd ios
          # Get the latest build number
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "net.coventry.sleepless")
          NEXT_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEXT_BUILD_NUMBER
      - name: Run unit tests
        script: |
          flutter test --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      - name: Upload iOS debug symbols
        script: |
          curl -sL https://firebase.tools | bash
          cd ios
          firebase crashlytics:symbols:upload \
            --app=1:19411767388:ios:f3c2574fbd3b8fcc391699 \
            ../build/ios/Release-iphoneos
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false