workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - production
      vars:
        PACKAGE_NAME: "net.coventry.sleepless"
      flutter: stable
    scripts:
      - name: Run unit tests
        script: |
          flutter test --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Build APK
        script: |
          flutter build apk --release \
            --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - production
      ios_signing:
        distribution_type: app_store
        bundle_identifier: net.coventry.sleepless
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Run unit tests
        script: |
          flutter test --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define=GF_GET_AUDIO_URL=$GF_GET_AUDIO_URL
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - loganvaleski@gmail.com
          - jvaleski@gmail.com
        notify:
          success: true
          failure: false