name: sleepless_app
description: sleepless app
publish_to: 'none'

version: 0.2.1+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_svg: ^2.0.14
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  firebase_core: ^3.11.0
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2
  audio_session: ^0.1.25
  rxdart: any
  url_launcher: ^6.3.1
  purchases_flutter: ^8.4.5
  purchases_ui_flutter: ^8.4.5
  logger: ^2.5.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  go_router: ^15.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.25.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    #- assets/audios/
    - assets/icons/
    - assets/resources.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
