name: sleepless_app
description: sleepless app
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter

  cyclic_dependency_checks:
    git:
      url: https://github.com/dam5s/cyclic_dependency_checks.git
      ref: release/0.1.0

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  logger: ^2.1.0
  intl: ^0.19.0
  flutter_svg: 2.0.10+1
  animated_segmented_tab_control: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    #- assets/audios/
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
